language: python
python:
  - "3.6"

notifications:
  email: false

install:
    - pip install -q cython numpy networkx scipy scikit-learn pandas
    - python setup.py build_ext --inplace

script:
  - pytest gmatch4py/test/test.py